# Generated by Django 5.0.11 on 2025-03-05 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('AUTORIZADO', 'autorizado'), ('LECTURA', 'lectura'), ('NO AUTORIZADO', 'no autorizado')], default='NO AUTORIZADO', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaeCargos',
            fields=[
                ('cargo', models.CharField(default='Sistemas', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'Cargos en la empresa',
                'verbose_name_plural': 'Cargos en la empresa',
                'db_table': 'maeCargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaeLugar',
            fields=[
                ('lugar', models.CharField(default='Sistemas', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'Lugar en la empresa',
                'verbose_name_plural': 'Lugar en la empresa',
                'db_table': 'maeLugar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OCRD',
            fields=[
                ('CardCode', models.CharField(db_column='CardCode', max_length=120, primary_key=True, serialize=False)),
                ('CardName', models.CharField(db_column='CardName', max_length=120)),
                ('CardType', models.CharField(db_column='CardType', default='No especifico', max_length=120)),
                ('validFor', models.CharField(blank=True, db_column='validFor', max_length=120, null=True)),
                ('GroupCode', models.IntegerField(blank=True, db_column='GroupCode', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OITM',
            fields=[
                ('Itemcode', models.CharField(db_column='ItemCode', max_length=120, primary_key=True, serialize=False)),
                ('ItemName', models.CharField(blank=True, db_column='ItemName', max_length=120, null=True)),
                ('ItmsGrpCod', models.IntegerField(db_column='ItmsGrpCod')),
            ],
        ),
        migrations.CreateModel(
            name='ORTT',
            fields=[
                ('RateDate', models.DateTimeField(db_column='RateDate')),
                ('Currency', models.CharField(db_column='Currency', max_length=120, primary_key=True, serialize=False)),
                ('Rate', models.DecimalField(db_column='Rate', decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('acceso', models.CharField(max_length=60)),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Idm', to='app.modulos')),
            ],
        ),
        migrations.CreateModel(
            name='OINV',
            fields=[
                ('Docentry', models.IntegerField(db_column='Docentry', primary_key=True, serialize=False)),
                ('DocNum', models.IntegerField(db_column='DocNum')),
                ('DocTotal', models.DecimalField(db_column='DocTotal', decimal_places=2, max_digits=10)),
                ('VatSum', models.DecimalField(db_column='VatSum', decimal_places=2, max_digits=10)),
                ('DocDate', models.DateTimeField(db_column='DocDate')),
                ('DiscPrcnt', models.DecimalField(db_column='DiscPrcnt', decimal_places=2, max_digits=10)),
                ('ObjType', models.CharField(db_column='ObjType', max_length=120)),
                ('OCRD_CardCode', models.ForeignKey(db_column='CardCode', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='C', to='app.ocrd')),
            ],
        ),
        migrations.CreateModel(
            name='INV1',
            fields=[
                ('DocEntry', models.IntegerField(db_column='DocEntry', primary_key=True, serialize=False)),
                ('Itemcode', models.IntegerField(db_column='Itemcode')),
                ('Quantity', models.IntegerField(db_column='Quantity')),
                ('LineTotal', models.IntegerField(db_column='LineTotal')),
                ('GrossBuyPr', models.DecimalField(db_column='GrossBuyPr', decimal_places=4, max_digits=10)),
                ('BaseEntry', models.CharField(db_column='BaseEntry', max_length=120)),
                ('BaseType', models.CharField(db_column='BaseType', max_length=120)),
                ('TrgetEntry', models.CharField(db_column='TrgetEntry', max_length=120)),
                ('DoCnum', models.ForeignKey(db_column='DoCnum', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nd', to='app.oinv')),
                ('OITM_ItemCode', models.ForeignKey(db_column='OITM_ItemCode', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OP', to='app.oitm')),
            ],
        ),
        migrations.CreateModel(
            name='OITW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OnHand', models.IntegerField(db_column='OnHand')),
                ('WhsCode', models.CharField(db_column='WhsCode', max_length=120)),
                ('AvgPrice', models.DecimalField(db_column='AvgPrice', decimal_places=4, max_digits=10)),
                ('Itemcode', models.ForeignKey(db_column='Itemcode', on_delete=django.db.models.deletion.PROTECT, related_name='n_items', to='app.oitm')),
            ],
        ),
        migrations.CreateModel(
            name='OQUT',
            fields=[
                ('DocTotal', models.DecimalField(db_column='DocTotal', decimal_places=2, max_digits=10)),
                ('VatSum', models.DecimalField(db_column='VatSum', decimal_places=2, max_digits=10)),
                ('CardCode', models.CharField(db_column='CardCode', max_length=120)),
                ('DocDate', models.DateTimeField(db_column='DocDate')),
                ('DiscPrcnt', models.DecimalField(db_column='DiscPrcnt', decimal_places=2, max_digits=10)),
                ('DocEntry', models.CharField(db_column='DocEntry', default='0', max_length=120, primary_key=True, serialize=False)),
                ('ObjType', models.CharField(db_column='ObjType', max_length=50)),
                ('OCRD_CardCode', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CI', to='app.ocrd')),
            ],
        ),
        migrations.CreateModel(
            name='ORDR',
            fields=[
                ('DocTotal', models.DecimalField(db_column='DocTotal', decimal_places=2, max_digits=10)),
                ('VatSum', models.DecimalField(db_column='VatSum', decimal_places=2, max_digits=10)),
                ('CardCode', models.CharField(db_column='CardCode', max_length=120)),
                ('DocDate', models.DateTimeField(db_column='DocDate')),
                ('DiscPrcnt', models.DecimalField(db_column='DiscPrcnt', decimal_places=2, max_digits=10)),
                ('DocEntry', models.CharField(db_column='DocEntry', max_length=120, primary_key=True, serialize=False)),
                ('ObjType', models.CharField(db_column='ObjType', max_length=120)),
                ('OCRD_CardCode', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CO', to='app.ocrd')),
            ],
        ),
        migrations.CreateModel(
            name='ORIN',
            fields=[
                ('DocTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VatSum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CardCode', models.CharField(max_length=120)),
                ('DocDate', models.DateTimeField()),
                ('DiscPrcnt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DocEntry', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('ObjType', models.CharField(max_length=120)),
                ('OCRD_CardCode', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CD', to='app.ocrd')),
            ],
        ),
        migrations.CreateModel(
            name='OWHS',
            fields=[
                ('WhsCode', models.CharField(db_column='WhsCode', max_length=120, primary_key=True, serialize=False)),
                ('OnHand', models.IntegerField(blank=True, db_column='OnHand', null=True)),
                ('WhsName', models.CharField(db_column='WhsName', max_length=120)),
                ('Itemcode', models.ForeignKey(blank=True, db_column='Itemcode', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_items', to='app.oitm')),
            ],
            options={
                'verbose_name': 'Maestro de bodegas',
                'verbose_name_plural': 'Maestro de bodegas',
                'db_table': 'OWHS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_perfil', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('modulos', models.ManyToManyField(related_name='perfiles', to='app.modulos')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('departamento', models.CharField(max_length=30)),
                ('perfil', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='app.perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='QUT1',
            fields=[
                ('DocEntry', models.IntegerField(db_column='DocEntry', default='None', primary_key=True, serialize=False)),
                ('Itemcode', models.IntegerField(db_column='Itemcode')),
                ('Quantity', models.IntegerField(db_column='Quantity')),
                ('LineTotal', models.IntegerField(db_column='LineTotal')),
                ('GrossBuyPr', models.DecimalField(db_column='GrossBuyPr', decimal_places=2, max_digits=10)),
                ('BaseEntry', models.CharField(db_column='BaseEntry', max_length=120)),
                ('BaseType', models.CharField(db_column='BaseType', max_length=120)),
                ('TrgetEntry', models.CharField(db_column='TrgetEntry', max_length=120)),
                ('OITM_ItemCode', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OE', to='app.oitm')),
                ('OQUT_DocEntry', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qut1_entries', to='app.oqut')),
            ],
        ),
        migrations.CreateModel(
            name='RDR1',
            fields=[
                ('DocEntry', models.IntegerField(default='None', primary_key=True, serialize=False)),
                ('Itemcode', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('LineTotal', models.IntegerField()),
                ('GrossBuyPr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BaseEntry', models.CharField(max_length=120)),
                ('BaseType', models.CharField(max_length=120)),
                ('TrgetEntry', models.CharField(max_length=120)),
                ('OITM_ItemCode', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OI', to='app.oitm')),
                ('ORDR_DocEntry', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cno', to='app.ordr')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Perfiles_Modulos',
            fields=[
                ('track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('parent_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='es', to='app.estado')),
                ('id_detalle_mod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Iddm', to='app.detallemodulo')),
                ('id_perfil', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='E', to='app.perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='RIN1',
            fields=[
                ('DocEntry', models.IntegerField(default='None', primary_key=True, serialize=False)),
                ('Itemcode', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('LineTotal', models.IntegerField()),
                ('GrossBuyPr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BaseEntry', models.CharField(max_length=120)),
                ('BaseType', models.CharField(max_length=120)),
                ('TrgetEntry', models.CharField(max_length=120)),
                ('OITM_ItemCode', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='O', to='app.oitm')),
                ('ORIN_DocEntry', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='c', to='app.orin')),
            ],
        ),
    ]
