# Generated by Django 5.0.11 on 2025-03-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ortt',
            name='Currency',
            field=models.CharField(db_column='Currency', max_length=3),
        ),
        migrations.AlterField(
            model_name='ortt',
            name='RateDate',
            field=models.DateTimeField(db_column='RateDate', primary_key=True, serialize=False),
        ),
    ]
