# Generated by Django 5.0.11 on 2025-03-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oinv',
            name='CardName',
            field=models.CharField(db_column='CardName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup1',
            field=models.BooleanField(db_column='QryGroup1', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup10',
            field=models.BooleanField(db_column='QryGroup10', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup11',
            field=models.BooleanField(db_column='QryGroup11', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup12',
            field=models.BooleanField(db_column='QryGroup12', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup13',
            field=models.BooleanField(db_column='QryGroup13', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup14',
            field=models.BooleanField(db_column='QryGroup14', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup15',
            field=models.BooleanField(db_column='QryGroup15', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup16',
            field=models.BooleanField(db_column='QryGroup16', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup17',
            field=models.BooleanField(db_column='QryGroup17', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup18',
            field=models.BooleanField(db_column='QryGroup18', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup19',
            field=models.BooleanField(db_column='QryGroup19', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup2',
            field=models.BooleanField(db_column='QryGroup2', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup20',
            field=models.BooleanField(db_column='QryGroup20', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup21',
            field=models.BooleanField(db_column='QryGroup21', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup22',
            field=models.BooleanField(db_column='QryGroup22', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup23',
            field=models.BooleanField(db_column='QryGroup23', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup24',
            field=models.BooleanField(db_column='QryGroup24', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup25',
            field=models.BooleanField(db_column='QryGroup25', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup26',
            field=models.BooleanField(db_column='QryGroup26', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup27',
            field=models.BooleanField(db_column='QryGroup27', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup28',
            field=models.BooleanField(db_column='QryGroup28', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup29',
            field=models.BooleanField(db_column='QryGroup29', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup3',
            field=models.BooleanField(db_column='QryGroup3', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup30',
            field=models.BooleanField(db_column='QryGroup30', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup31',
            field=models.BooleanField(db_column='QryGroup31', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup32',
            field=models.BooleanField(db_column='QryGroup32', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup33',
            field=models.BooleanField(db_column='QryGroup33', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup34',
            field=models.BooleanField(db_column='QryGroup34', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup35',
            field=models.BooleanField(db_column='QryGroup35', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup36',
            field=models.BooleanField(db_column='QryGroup36', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup37',
            field=models.BooleanField(db_column='QryGroup37', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup38',
            field=models.BooleanField(db_column='QryGroup38', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup39',
            field=models.BooleanField(db_column='QryGroup39', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup4',
            field=models.BooleanField(db_column='QryGroup4', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup40',
            field=models.BooleanField(db_column='QryGroup40', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup41',
            field=models.BooleanField(db_column='QryGroup41', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup42',
            field=models.BooleanField(db_column='QryGroup42', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup43',
            field=models.BooleanField(db_column='QryGroup43', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup44',
            field=models.BooleanField(db_column='QryGroup44', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup45',
            field=models.BooleanField(db_column='QryGroup45', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup46',
            field=models.BooleanField(db_column='QryGroup46', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup47',
            field=models.BooleanField(db_column='QryGroup47', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup48',
            field=models.BooleanField(db_column='QryGroup48', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup49',
            field=models.BooleanField(db_column='QryGroup49', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup5',
            field=models.BooleanField(db_column='QryGroup5', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup50',
            field=models.BooleanField(db_column='QryGroup50', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup51',
            field=models.BooleanField(db_column='QryGroup51', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup52',
            field=models.BooleanField(db_column='QryGroup52', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup53',
            field=models.BooleanField(db_column='QryGroup53', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup54',
            field=models.BooleanField(db_column='QryGroup54', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup55',
            field=models.BooleanField(db_column='QryGroup55', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup56',
            field=models.BooleanField(db_column='QryGroup56', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup57',
            field=models.BooleanField(db_column='QryGroup57', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup58',
            field=models.BooleanField(db_column='QryGroup58', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup59',
            field=models.BooleanField(db_column='QryGroup59', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup6',
            field=models.BooleanField(db_column='QryGroup6', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup60',
            field=models.BooleanField(db_column='QryGroup60', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup61',
            field=models.BooleanField(db_column='QryGroup61', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup62',
            field=models.BooleanField(db_column='QryGroup62', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup63',
            field=models.BooleanField(db_column='QryGroup63', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup64',
            field=models.BooleanField(db_column='QryGroup64', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup7',
            field=models.BooleanField(db_column='QryGroup7', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup8',
            field=models.BooleanField(db_column='QryGroup8', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='QryGroup9',
            field=models.BooleanField(db_column='QryGroup9', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oitw',
            name='AvgPrice',
            field=models.DecimalField(db_column='AvgPrice', decimal_places=4, max_digits=10, null=True),
        ),
    ]
