# Generated by Django 5.0.11 on 2025-02-03 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('AUTORIZADO', 'autorizado'), ('LECTURA', 'lectura'), ('NO AUTORIZADO', 'no autorizado')], default='NO AUTORIZADO', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_perfil', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('glosa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('acceso', models.CharField(max_length=60)),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Idm', to='app.modulos')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('departamento', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=60)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Idp', to='app.perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Perfiles_Modulos',
            fields=[
                ('track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('parent_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('estado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='es', to='app.estado')),
                ('id_empleado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='E', to='app.empleados')),
                ('tipoMenu', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='T', to='app.tipomenu')),
            ],
        ),
    ]
