# Generated by Django 5.0.11 on 2025-04-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuarios_options_alter_usuarios_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Branch',
            field=models.SmallIntegerField(blank=True, db_column='Branch', null=True),
        ),
    ]
