# Generated by Django 5.0.11 on 2025-02-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estado_modulos_detallemodulo_perfiles_empleados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_empleado',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
