# Generated by Django 5.0.11 on 2025-03-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_oinv_discprcnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ortt',
            name='Rate',
            field=models.DecimalField(db_column='Rate', decimal_places=6, max_digits=19),
        ),
    ]
