# Generated by Django 5.0.11 on 2025-02-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_empleados_cargo_alter_empleados_id_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrd',
            name='GroupCode',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oitm',
            name='ItmsGrpCod',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oitw',
            name='AvgPrice',
            field=models.DecimalField(decimal_places=4, default=20000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oitw',
            name='WhsCode',
            field=models.CharField(default=234, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owhs',
            name='WhsName',
            field=models.CharField(default=123456789, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inv1',
            name='BaseEntry',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='BaseType',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='DocEntry',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='GrossBuyPr',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inv1',
            name='TrgetEntry',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='CardCode',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='CardName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='CardType',
            field=models.CharField(default='No especifico', max_length=120),
        ),
        migrations.AlterField(
            model_name='ocrd',
            name='validFor',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='DocNum',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oinv',
            name='ObjType',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='oitm',
            name='ItemName',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='CardCode',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='oqut',
            name='DocEntry',
            field=models.CharField(default='0', max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='CardCode',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='DocEntry',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='ObjType',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='orin',
            name='CardCode',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='orin',
            name='DocEntry',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orin',
            name='ObjType',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ortt',
            name='Currency',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ortt',
            name='Rate',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='owhs',
            name='WhsCode',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='BaseEntry',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='BaseType',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='DocEntry',
            field=models.CharField(default='None', max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qut1',
            name='TrgetEntry',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='BaseEntry',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='BaseType',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='DocEntry',
            field=models.CharField(default='None', max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rdr1',
            name='TrgetEntry',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='rel_perfiles_modulos',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='rin1',
            name='BaseEntry',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='rin1',
            name='BaseType',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='rin1',
            name='DocEntry',
            field=models.CharField(default='None', max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rin1',
            name='TrgetEntry',
            field=models.CharField(max_length=120),
        ),
    ]
