# Generated by Django 5.0.11 on 2025-02-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ocrd_groupcode_oitm_itmsgrpcod_oitw_avgprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oitm',
            name='Itemcode',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
