# Generated by Django 5.0.11 on 2025-03-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ortt_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrd',
            name='GroupCode',
            field=models.SmallIntegerField(blank=True, db_column='GroupCode', null=True),
        ),
    ]
