# Generated by Django 5.0.11 on 2025-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_oitm_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oitm',
            name='ItemName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
