# Generated by Django 5.0.11 on 2025-02-26 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_oitm_itemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owhs',
            name='Itemcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_items', to='app.oitm'),
        ),
    ]
